stages:
  - build
  - deploy

aws_pull:
  stage: build
  only:
    - development
    - master
  tags:
    - Engima
  script:
    - 'whoami'
    - 'cd /home/gitlab-runner/engima'
    - 'echo "Start pull dari repo"'
    - 'git stash'
    - 'git checkout development'
    - 'git pull origin development'
    - 'echo "Done pull dari repo"'

aws_lint:
  stage: build
  only:
    - development
    - master
  tags:
    - Engima
  script:
    - 'whoami'
    - 'cd /home/gitlab-runner/engima'
    - './vendor/bin/phplint'

aws_deploy:
  stage: deploy
  only:
    - development
    - master
  tags:
    - Engima
  script:
    - 'echo "Automated deploy karena sudah ada symbolic link di htdocs"'